### ISSUE TITLE
Replace 'torba' with 'torba-rails'

### ISSUE THREAD

**Issue by JakeSchoermer** [ausaccessfed/aaf-lipstick#58]
There is a need to replace `torba` gem with `torba-rails` gem as a required dependency in the **README** for `aaf-lipstick` when used with rails.

This is inline with the [current documentation](https://github.com/torba-rb/torba) for the `torba` gem.

Currently if the `torba` gem is used, a sprockets error is raised in rails projects using the the latest version of that gem with `aaf-lipstick`.

**Comment by smangelsdorf** [comment]
Out of interest, what's the error raised by sprockets?

**Comment by JakeSchoermer** [comment]
This is the error I was getting:

![screen shot 2016-04-21 at 11 14 16 am](https://cloud.githubusercontent.com/assets/591909/14695128/75e0bbd8-07b2-11e6-8db3-e2895163ac8a.png)

Now, I should also add, that even after adding the `torba-rails` gem, I had to add `require 'torba/rails'` to my `application.rb`. I ported this over from a previous app, but I'm almost certain that this was in the documentation either for this gem or in torba's doc.
