### ISSUE TITLE
Version String broken

### ISSUE THREAD

**Issue by JakeSchoermer** [ausaccessfed/aaf-lipstick#59]
When implementing the provided [sample layout](https://github.com/ausaccessfed/aaf-lipstick/blob/develop/sample/rails/app/views/layouts/application.html.slim) referred to in the documentation, the version string does not print. Instead a `uninitialized constant Lipstick::VERSION` constant is raised.

![screen shot 2016-05-04 at 4 41 04 pm](https://cloud.githubusercontent.com/assets/591909/15006928/d27964ca-1217-11e6-8712-6b1beaca11df.png)

**Comment by smangelsdorf** [comment]
`Lipstick::VERSION` is the gem version, and likely not what you want. The sample layout is a starting point, but should be entirely customised to the individual application before being committed.

Technically this is a bug, as the `lipstick/version` file **should** be required. However, this is only going to mask the larger problem of blindly copied code. I've tweaked the wording in the README to serve as an additional prompt in future.

**Comment by JakeSchoermer** [comment]
This approach sounds fine to me. I'd be just as open to dropping the version completely, but I'm happy either way.
