### ISSUE TITLE
Validations should be numbered and reference the field in error

### ISSUE THREAD

**Issue by bradleybeddoes** [ausaccessfed/aaf-lipstick#9]
This:

```
<%= validate_form('#project-form', :project) do -%>
  <%= validate_field(:name, empty: 'Please provide the projects name') %>
  <%= validate_field(:provider_arn, provider_arn: message) %>
<%- end -%>
```

Results in:
![wtf?](http://i.imgur.com/wrX8K2i.png)

Which isn't very readable.

Naturally I might be using this incorrectly :see_no_evil:

**Comment by smangelsdorf** [comment]
In that example, the `message` is being copied verbatim into the validation errors. You need to provide a message which suits the purpose better.

Might be a good idea to make the errors show as dot points though (numbering is cool but the numbers would have no meaning at all).

**Comment by bradleybeddoes** [comment]
Dot points would suffice, just needs to be visually broken up better
